services:
  webserver:
    build: ./nginx
    container_name: webserver
    volumes:
      - ./logs/error.log:/var/log/nginx/error.log
      - ./logs/access.log:/var/log/nginx/access.log
    networks:
      - proyecto_monitoring_net
    ports:
      - "8080:80"

  fail2ban:
    build: ./fail2ban
    container_name: fail2ban
    volumes:
      - ./logs/access.log:/var/log/nginx/access.log:ro
      - ./fail2ban/jail.local:/etc/fail2ban/jail.local:ro
      - ./fail2ban/filter.d:/etc/fail2ban/filter.d:ro
    networks:
      - proyecto_monitoring_net
    cap_add:
      - NET_ADMIN
      - NET_RAW
    privileged: true

networks:
  proyecto_monitoring_net:
    driver: bridge
