version: '3.8'

services:
  port-scan-detector:
    build:
      context: .
      dockerfile: Dockerfile
    image: port-scan-detector
    container_name: nmap-detector
    network_mode: host
    cap_add:
      - NET_RAW
      - NET_ADMIN
    volumes:
      - ./logs/scan:/logs
    environment:
      - THRESHOLD=15
      - TIME_WINDOW=5
