services:
  suricata:
    build: ./suri
    container_name: suricata
    network_mode: host
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      # Verifica que este archivo NO esté vacío antes de montar
      - ./suri/conf/suricata.yaml:/etc/suricata/suricata.yaml
      - ./suri/conf/rules:/etc/suricata/rules
      # Descomenta si ya tienes estos archivos configurados correctamente
      # - ./suri/conf/classification.config:/etc/suricata/classification.config
      # - ./suri/conf/threshold.config:/etc/suricata/threshold.config
      - ./suri/logs:/var/log/suricata
      - ./suri/lib/suricata-lib:/var/lib/suricata
    stdin_open: true
    tty: true

